name: graphql_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  angel3_container: ^7.0.0
  angel3_framework: ^7.0.3
  angel3_graphql: ^7.0.0
  angel3_serialize: ^7.0.0
  graphql_generator2: ^5.1.0
  graphql_schema2: ^5.0.0
  graphql_server2: ^5.0.0
  sqlite3: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.0
